### ISSUE TITLE
Verify Node Approval System

### ISSUE THREAD

**Issue by nfeld9807** [gladiusio/gladius-marketplace-backend#22]
Logic flow:

- Node sent to "pending" list
- Node approved
- Node added to Pool

**Comment by nfeld9807** [comment]
The owner is the only one allowed to view this list for their Pools

**Comment by nfeld9807** [comment]
The owner is the only one allowed to view this list for their Pools

**Comment by Noobperson** [comment]
I have a question concerning this. Will the node send some tokens to the smart contract to be able to join the gladius network?

**Comment by Celo44** [comment]
Yes
